backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
collections:
  - name: "website_components"
    label: "Components"
    files:
      - name: "top_nav"
        label: "Top Navigation"
        file: "content/components/top_nav.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - name: "links"
            label: "Links"
            widget: list
            types:
              - label: "Links"
                name: "links"
                widget: object
                summary: "{{fields.display_text}}"
                fields:
                  - { name: "display_text", label: "Display Text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
      - name: "footer"
        label: "Footer"
        file: "content/components/footer.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - name: "links"
            label: "Links"
            widget: list
            types:
              - label: "Links"
                name: "links"
                widget: object
                summary: "{{fields.display_text}}"
                fields:
                  - { name: "display_text", label: "Display Text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
      - name: "filters"
        label: "Filters"
        file: "content/components/filters.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - name: filters
            label: Filters
            widget: list
            field: { label: Filter, name: filter, widget: string }
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Headline", name: "headline", widget: "markdown" }
          - { label: "Information", name: "information", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Information", name: "information", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Clients", name: "clients", widget: "markdown" }
          - name: "resume"
            label: "Page Resume"
            widget: object
            summary: "{{fields.display_text}}"
            fields:
              - { name: "resume_text", label: "Resume Text", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
          - name: "cta"
            label: "Call To Action"
            widget: object
            summary: "{{fields.display_text}}"
            fields:
              - { name: "display_text", label: "Display Text", widget: "string" }
              - { name: "contact_text", label: "Contact Text", widget: "string" }
              - { name: "contact_link", label: "Contact Link", widget: "string" }
  - name: "featured"
    label: "Featured Projects"
    folder: "content/featured"
    create: true
    identifier_field: name
    sortable_fields: ["index"]
    fields:
      - { label: "Index", name: "index", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Challenge", name: "challenge", widget: "markdown" }
      - { label: "Solution", name: "solution", widget: "markdown" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - {
          label: "Image Text",
          name: "image_text",
          widget: "string",
          required: false,
        }
      - name: "link"
        label: "Link"
        widget: object
        summary: "{{fields.link_text}}"
        fields:
          - {
              name: "link_text",
              label: "Link Text",
              widget: "string",
              required: false,
            }
          - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "In Progress?", name: "in_progress", widget: "boolean" }
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    identifier_field: name
    sortable_fields: ["index"]
    fields:
      - { label: "Index", name: "index", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Project Date", name: "date", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Cover Image", name: "cover_image", widget: "image" }
      - name: accordion_sections
        label: Accordion Sections
        widget: list
        types:
          - name: section
            label: Section
            widget: object
            summary: "{{fields.header}}"
            fields:
              - { name: header, label: Header, widget: string }
              - { name: content, label: Content, widget: markdown }
      - name: body_sections
        label: Body Sections
        widget: list
        types:
          - name: section
            label: Section
            widget: object
            summary: "{{fields.header}}"
            fields:
              - { name: header, label: Header, widget: string }
              - name: content
                label: Content
                widget: list
                types:
                  - name: content_block
                    label: Content Block
                    widget: object
                    summary: "{{fields.content}}"
                    fields:
                      - { name: content_data, label: Content Data, widget: markdown }
                      - {
                          name: lwidth,
                          label: Layout Width,
                          widget: string,
                          default: "full",
                        }
              - { name: image, label: Image, widget: image, required: false }
              - { name: video, label: Video ID, widget: string, required: false }
      - name: gallery
        label: Gallery
        required: false
        widget: list
        field: { label: Image, name: image, widget: image }
