backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "website_components"
    label: "Components"
    files:
      - name: "top_nav"
        label: "Top Navigation"
        file: "content/components/top_nav.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - name: "links"
            label: "Links"
            widget: list
            types:
              - label: "Links"
                name: "links"
                widget: object
                summary: "{{fields.display_text}}"
                fields:
                  - { name: "display_text", label: "Display Text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
      - name: "footer"
        label: "Footer"
        file: "content/components/footer.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - name: "links"
            label: "Links"
            widget: list
            types:
              - label: "Links"
                name: "links"
                widget: object
                summary: "{{fields.display_text}}"
                fields:
                  - { name: "display_text", label: "Display Text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Headline", name: "headline", widget: "markdown" }
          - { label: "Information", name: "information", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Information", name: "information", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
          - name: "cta"
            label: "Call To Action"
            widget: object
            summary: "{{fields.display_text}}"
            fields:
              - { name: "display_text", label: "Display Text", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
          - name: "resume"
            label: "Resume"
            widget: object
            summary: "{{fields.display_text}}"
            fields:
              - {
                  name: "resume_text",
                  label: "Resume Display Text",
                  widget: "string",
                }
              - { label: "Link", name: "link", widget: "string" }
  - name: "featured"
    label: "Featured Projects"
    folder: "content/featured"
    create: true
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image Text", name: "image_text", widget: "string" }
      - name: "link"
        label: "Link"
        widget: object
        summary: "{{fields.link_text}}"
        fields:
          - { name: "link_text", label: "Link Text", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
      - { label: "In Progress?", name: "in_progress", widget: "boolean" }
